### ISSUE TITLE
Pijuice has ONLY menu and nothing else in pi 5...

### ISSUE THREAD

**Issue by Omnipresent77** [PiSupply/PiJuice#1101]
Pijuice has ONLY menu saying 'pijuice settings.'

No tray icon, no GUI nothing after installing the GUI.

Running latest and updated rasbian on a pi 5 with 8 GB of ram.

Thought to start a new issue as i have seen a few things ( like ffmeg? ) not run on pi 5 now....

trying that deletion of the linked files and relinking them to the 32 version OR the 6 version either did not work.

no error that i can see when trying to run it from terminal happens. noting happens.

**Comment by Omnipresent77** [comment]
So the Pijuice has a old school d type micro usb connector. The pi 5 has a USB c. I just got a message on screen on boot up that the power supply can not supply the 5A the pi 5 needs.

**Comment by Omnipresent77** [comment]
So I uninstalled and reinstalled the PiJuice gui today.
I got the following error (twice one right after the other) while installing.
chown: warning ' . ' should be ' :' 'pijuice.pijuice'

**Comment by Omnipresent77** [comment]
running at terminal: systemctl status pijuice.service
I get:
* pijuice.service - PiJuice status service
     Loaded: loaded (/lib/systemd/system/pijuice.service; disabled; preset: ena>
     Active: inactive (dead)

**Comment by Omnipresent77** [comment]
> So I uninstalled and reinstalled the PiJuice gui today. I got the following error (twice one right after the other) while installing. chown: warning ' . ' should be ' :' 'pijuice.pijuice'

2022-02-24
+  chown and chroot now warn about usages like "chown root.root f",
+  which have the nonstandard and long-obsolete "." separator that
+  causes problems on platforms where user names contain ".".
+  Applications should use ":" instead of ".".

So is the script now outdated and needs to be updated to this standard or what??

**Comment by Omnipresent77** [comment]
I was able to get the cli to work, and confirm firmware version 1.6 on the pi supply

**Comment by Omnipresent77** [comment]
It appears ALL of the following 14 pijuice files are root owner and group. Do they need to be pijuice pijuice as that error looks to be above?

pijuiceboot
pijuiceboot32
pijuiceboot64
pijuice_cli
pijuice_cli32
pijuice_cli64
pijuice_cli.py
pijuice_gui
pijuice_gui32
pijuice_gui64
pijuice_gui.py
pijuice_log.py
pijuice_sys.py
pijuice_tray.py

Changed them to user user except even after deletion of the linked 3 and recreating them. they staid as root root.

changed the epprom address  to 52 (as i did have a media center hat software but no longer hardware)

the Setting window does now appear, but will not close and the system tray power icon is NOT there still

**Comment by Omnipresent77** [comment]
running from the terminal: pijuice_tray.py
results in:
Traceback (most recent call last):
  File "/usr/bin/pijuice_tray.py", line 182, in <module>
    with open(TRAY_PID_FILE, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/pijuice_tray.pid'

also running from the terminal pijuice_sys.py
results in:
Traceback (most recent call last):
  File "/usr/bin/pijuice_sys.py", line 425, in <module>
    main()
  File "/usr/bin/pijuice_sys.py", line 319, in main
    with open(configPath, 'w+') as conf_f:
         ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/lib/pijuice/pijuice_config.JSON'

or ANY file in /var/lib/pijuice/*.* with owner of said pijuicesys.py file set to pijuie pijuice or user user

so yes settings are now openable, but non closable window. While as the system tray battery indicator is not there now

**Comment by Omnipresent77** [comment]
rest of the issue of no tray icon continued in...

https://github.com/PiSupply/PiJuice/issues/1094
