### ISSUE TITLE
SOLVED: "Unable to connect to device", No LEDs, no software (V0.0)

### ISSUE THREAD

**Issue by Reefkeeper** [PiSupply/PiJuice#183]
With my Raspberry Pi 3B+ (Stretch Lite) my first PiJuice worked fine.
I copied the Raspi image to use it for further PiJuices, so far so good.

I have now bought 3 more PiJuices, and with 2 of them (I haven't the courage to try the 3rd one) I cannot get it work. The SD card image is the same as with the first one, which means **I did not install the PiJuice software with the new PiJuices (is this important?), I merely inserted a completely new PiJuice into a working Raspberry Pi.**
If I start PiJuice_cli.py -> Status  I get these error messages:
```
 pijuice_cli.py
Traceback (most recent call last):
  File "/usr/bin/pijuice_cli.py", line 1320, in <module>
    loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 592, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 464, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/bin/pijuice_cli.py", line 1255, in item_chosen
    callback()
  File "/usr/bin/pijuice_cli.py", line 65, in __init__
    self.main()
  File "/usr/bin/pijuice_cli.py", line 120, in main
    status_args = self.get_status()
  File "/usr/bin/pijuice_cli.py", line 83, in get_status
    gpio_info = "%.3fV, %.3fA, %s" % (io_voltage / 1000, io_current / 1000, status['powerInput5vIo'])
KeyError: 'powerInput5vIo'
```
When I click on "General" I get "unable to connect to device".
And  ```
i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
The I2C interface is enabled (it's the same Raspi image, remember).

The software version shows V 0.0.
The battery works as it powers up the Pi as soon as it is attached to the Pi. 
No LED is showing.
If I use the first PiJuice, everything works fine on the Raspberry. 
Are there any serial numbers in the PiJuice which prevent them to be interchanged?

Can someone suggest any help, please?

**Comment by Reefkeeper** [comment]
See above, problem was solved by manual boot loading firmware, s. link!
