### ISSUE TITLE
CLI crashes every time

### ISSUE THREAD

**Issue by DickesC** [PiSupply/PiJuice#236]
My PiJuice CLI is not working correct.

If i want to go into "General" i get the error "Unable to connect to device" and the CLI crashes with this error:

`Traceback (most recent call last):
  File "/usr/bin/pijuice_cli.py", line 1320, in <module>
    loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/bin/pijuice_cli.py", line 111, in update_status
    status_args = self.get_status()
  File "/usr/bin/pijuice_cli.py", line 83, in get_status
    gpio_info = "%.3fV, %.3fA, %s" % (io_voltage / 1000, io_current / 1000, status['powerInput5vIo'])
KeyError: 'powerInput5vIo'`

i2cdetect shows it correct at id 14 and 68

I have done a reset and a manual reflash of the PiJuice
What can i do?

**Comment by DickesC** [comment]
Nothing else connected.
I power it direct with the 5v input of the PiJuice.
Raspberry is a 3 B+
