### ISSUE TITLE
Can't upgrade firmware from pijuice_cli.py

### ISSUE THREAD

**Issue by jf-ch** [PiSupply/PiJuice#77]
I tried to upgrade the pijuice firmware thru pijuice_cli.py. I'm running ver 1.0 and it shows that ver 1.1 is available but I get an error message but I select the upgrade:
```Traceback (most recent call last):
  File "/usr/bin/pijuice_cli.py", line 1229, in <module>
    urwid.MainLoop(top, palette=[('reversed', 'standout', '')]).run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 339, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 669, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 706, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 390, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 490, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 588, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1583, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 464, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
TypeError: update_firmware() takes at most 2 arguments (3 given)
```

**Comment by DenisKhrutsky** [comment]
Fixed in [#33f3c6](https://github.com/PiSupply/PiJuice/commit/33f3c67fd90665a4dc9ddc9d9f16ce4a36baa8bd). New build with this fix is going to be deployed to raspbian repo today.
