### ISSUE TITLE
Programatically setting Button Config

### ISSUE THREAD

**Issue by track02** [PiSupply/PiJuice#793]
Hello,

I'm investigating using a script to configure PiJuice buttons automatically, but seem to have an issue applying a config, I've added a snippet below from some testing in the REPL

I'm able to request a config from a button but then trying to apply that config throws a key error
Is there something I'm missing in the configuration format? 

I've had a quick look through the source of pijuice.py but nothing jumps out

Any assistance would be appreciated

````
>>> from pijuice import PiJuice, PiJuiceConfig
>>> pijuice = PiJuice()
>>> button_1_conf = pijuice.config.GetButtonConfiguration("SW1")
>>> button_1_conf
{'data': {'PRESS': {'function': 'NO_FUNC', 'parameter': 0}, 'RELEASE': {'function': 'NO_FUNC', 'parameter': 0}, 'SINGLE_PRESS': {'function': 'HARD_FUNC_POWER_ON', 'parameter': 800}, 'DOUBLE_PRESS': {'function': 'NO_FUNC', 'parameter': 0}, 'LONG_PRESS1': {'function': 'SYS_FUNC_HALT_POW_OFF', 'parameter': 5000}, 'LONG_PRESS2': {'function': 'HARD_FUNC_POWER_OFF', 'parameter': 25000}}, 'error': 'NO_ERROR'}
>>> pijuice.config.SetButtonConfiguration("SW2", button_1_conf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pijuice.py", line 1325, in SetButtonConfiguration
    config[self.buttonEvents[i]]['function']) + 0x01
KeyError: 'PRESS'
````

**Comment by track02** [comment]
Nevermind!

Just me not reading closely enough, the config is the part under 'data' 

E.g. for any who needs it

````
>>> from pijuice import PiJuice, PiJuiceConfig
>>> pijuice = PiJuice()
>>> button_1_conf = pijuice.config.GetButtonConfiguration("SW1")
>>> pijuice.config.SetButtonConfiguration("SW2", button_1_conf["data"])
{'error': 'NO_ERROR'}
````
